### ISSUE TITLE
Add ability to use creds from Key Vault (or other native) for acct

### ISSUE THREAD

**Issue by nicholasmhughes** [eitrtechnologies/idem-azurerm#101]
If possible, allow acct to grab credentials from Key Vault (or external native secret store) to use for the purposes of authenticating for state runs. This is probably of limited use, because most people will just have managed identities assigned to a provisioning host which can just perform the actiosn directly. However, I think that it might fit a niche use case and is worthwhile.

I'm not certain exactly how this could be integrated into acct. Need to research further.

The main thing that should be considered, but probably will be hard is to leverage this functionality across different providers. For instance, using credentials stored in key vault to access an AWS subscription or conversely using credentials stored in AWS secrets manager to access Azure.

**Comment by tompscanlan** [comment]
Looks like this was handled in #112 and #114. Any additional work needed?

**Comment by nicholasmhughes** [comment]
Nope
